on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout
        run: actions/checkout@master

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run cy:run --spec "cypress/integration/calculatrice.spec.js"
